Hw7
ylnglmv/2nd-course-homework pull request #6
Opened 2023-07-13 13:01 UTC by ylnglmv

2023-07-14 13:14 UTC, Mielilon requested changes
Решение требует корректировок. 
Пожалуйста, протестируйте код перед отправкой.

2023-07-14 13:14 UTC, Mielilon commented on hw7.js
> +    return str.indexOf();
Задача решена не совсем корректно. Необходимо реализовать сравнение элементов массива со строкой без учета регистра.

Рекомендуется использовать метод `filter`, а также `toLowerCase` и `startsWith`.

2023-07-14 13:14 UTC, Mielilon commented on hw7.js
> +function getRandomArbitrary(1, 10) {
При объявлении функции нужно передавать не значения, а параметры-заглушки. При вызове вместо них будут поставлены значения.

2023-07-14 13:14 UTC, Mielilon commented on hw7.js
> +    return Math.random() * (10 - 1) + 1;
Соответственно тут нужно применить параметры функции.

2023-07-14 13:14 UTC, Mielilon commented on hw7.js
> +        array.push(Math.ceil(Math.random(num) * num));
Не совсем корректное решение. . Функция `Math.random` не принимает параметров.

2023-07-14 13:14 UTC, Mielilon commented on hw7.js
> +function getRandomArbitrary(5, 35) {
Функция должна принимать два параметра, а не конкретные значения.

2023-07-14 13:14 UTC, Mielilon commented on hw7.js
> +const days = ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"];
Обратите внимание на результат выполнения кода:
<img width="321" alt="image" src="https://github.com/ylnglmv/2nd-course-homework/assets/65778664/415be242-aedd-436c-822c-edf1e3cb132a">

Требуется поправить решение.

2023-07-14 13:14 UTC, Mielilon commented on hw7.js
> +function gameguess () {
Попробуйте запустить код функции. Сейчас внутри допущены опечатки, которые мешают ее работе.

Нужно поправить.

2023-07-16 11:42 UTC, ylnglmv commented on hw7.js
> +function getRandomArbitrary(5, 35) {
не понимаю, какие именно параметры поставить

2023-07-19 11:02 UTC, merged